add logging for docker login

diff --git a/.github/workflows/register_model.yml b/.github/workflows/register_model.yml
--- a/.github/workflows/register_model.yml
+++ b/.github/workflows/register_model.yml
@@ -170,8 +170,15 @@ jobs:
 
         # Create image name and version
         image="${model_name}_v${model_version}"
+        log_file="docker_login_error.log"
 
-        docker login -u "${{ secrets.JFROG_CONTAINER_REGISTRY_USERNAME }}" -p "${{ secrets.JFROG_CONTAINER_REGISTRY_PASSWORD }}" "${{ secrets.JFROG_CONTAINER_REGISTRY_HOST }}"
+        echo "${{ secrets.JFROG_CONTAINER_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.JFROG_CONTAINER_REGISTRY_USERNAME }}" --password-stdin "${{ secrets.JFROG_CONTAINER_REGISTRY_HOST }}" 2>> "$log_file"
 
+        if [ $? -ne 0 ]; then
+          echo "Docker login failed.
+          cat "$log_file"
+        else
+          echo "Docker login successful."
+        fi
         ./script/devops.sh publish_image --name "$image" --version "${{ env.RELEASE_VERSION }}" --channel "${{ env.RELEASE_CHANNEL }}" --registry "${{ secrets.JFROG_CONTAINER_REGISTRY_HOST }}" --namespace "${{ env.NAMESPACE}}"
         docker images
